-- Generado por Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   en:        2026-03-26 18:19:24 CST
--   sitio:      Oracle Database 21c
--   tipo:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ASIGNACION
    (
     ESTUDIANTE_CARNET   NUMBER (10)  NOT NULL ,
     SECCION_CODIGOCURSO NUMBER (5)  NOT NULL ,
     SECCION_SECCION     VARCHAR2 (5)  NOT NULL ,
     SECCION_ANIO        NUMBER (4)  NOT NULL ,
     SECCION_CICLO       VARCHAR2 (10)  NOT NULL ,
     ZONA                NUMBER (5,2) ,
     NOTA                NUMBER (5,2)
    )
    LOGGING
;

ALTER TABLE ASIGNACION
    ADD CONSTRAINT ASIGNACION_CK_1
    CHECK ( ADD CONSTRAINT CHK_ZONA_POSITIVA
    CHECK (ZONA >= 0 AND ZONA <= 100);

ADD CONSTRAINT CHK_NOTA_POSITIVA
    CHECK (NOTA >= 0 AND NOTA <= 100);)
;
ALTER TABLE ASIGNACION
    ADD CONSTRAINT ASIGNACION_PK PRIMARY KEY ( ESTUDIANTE_CARNET, SECCION_CODIGOCURSO, SECCION_SECCION, SECCION_ANIO, SECCION_CICLO ) ;

CREATE TABLE CARRERA
    (
     CARRERA NUMBER (5)  NOT NULL ,
     NOMBRE  VARCHAR2 (100)  NOT NULL
    )
    LOGGING
;

ALTER TABLE CARRERA
    ADD CONSTRAINT CARRERA_PK PRIMARY KEY ( CARRERA ) ;

CREATE TABLE CATEDRATICO
    (
     CATEDRATICO   NUMBER (5)  NOT NULL ,
     NOMBRE        VARCHAR2 (150)  NOT NULL ,
     SUELDOMENSUAL NUMBER (10,2)  NOT NULL
    )
    LOGGING
;

ALTER TABLE CATEDRATICO
    ADD CONSTRAINT CHK_SUELDO
    CHECK (SUELDOMENSUAL > 0)
;
ALTER TABLE CATEDRATICO
    ADD CONSTRAINT CATEDRATICO_PK PRIMARY KEY ( CATEDRATICO ) ;

CREATE TABLE CURSO
    (
     CODIGOCURSO NUMBER (5)  NOT NULL ,
     NOMBRECURSO VARCHAR2 (100)  NOT NULL
    )
    LOGGING
;

ALTER TABLE CURSO
    ADD CONSTRAINT CURSO_PK PRIMARY KEY ( CODIGOCURSO ) ;

CREATE TABLE DIA
    (
     DIA       NUMBER (1)  NOT NULL ,
     NOMBREDIA VARCHAR2 (20)  NOT NULL
    )
    LOGGING
;

ALTER TABLE DIA
    ADD CONSTRAINT CHK_DIA_NUM
    CHECK (DIA BETWEEN 1 AND 7)
;
ALTER TABLE DIA
    ADD CONSTRAINT DIA_PK PRIMARY KEY ( DIA ) ;

CREATE TABLE ESTUDIANTE
    (
     CARNET          NUMBER (10)  NOT NULL ,
     NOMBRE          VARCHAR2 (150)  NOT NULL ,
     INGRESOFAMILIAR NUMBER (12,2) ,
     FECHANACIMIENTO DATE
    )
    LOGGING
;

ALTER TABLE ESTUDIANTE
    ADD CONSTRAINT ESTUDIANTE_PK PRIMARY KEY ( CARNET ) ;

CREATE TABLE HORARIO
    (
     SECCION_CURSO_CODIGOCURSO NUMBER (5)  NOT NULL ,
     SECCION_SECCION           VARCHAR2 (5)  NOT NULL ,
     SECCION_ANIO              NUMBER (4)  NOT NULL ,
     SECCION_CICLO             VARCHAR2 (10)  NOT NULL ,
     PERIODO_PERIODO           NUMBER (5)  NOT NULL ,
     DIA_DIA                   NUMBER (1)  NOT NULL ,
     SALON_EDIFICIO            VARCHAR2 (10)  NOT NULL ,
     SALON_SALON               NUMBER (5)  NOT NULL
    )
    LOGGING
;

ALTER TABLE HORARIO
    ADD CONSTRAINT HORARIO_PK PRIMARY KEY ( SECCION_CURSO_CODIGOCURSO, SECCION_SECCION, SECCION_ANIO, SECCION_CICLO, PERIODO_PERIODO, DIA_DIA ) ;

CREATE TABLE INSCRIPCION
    (
     CARRERA          NUMBER (5)  NOT NULL ,
     CARNET           NUMBER (10)  NOT NULL ,
     FECHAINSCRIPCION DATE  NOT NULL
    )
    LOGGING
;

ALTER TABLE INSCRIPCION
    ADD CONSTRAINT INSCRIPCION_PK PRIMARY KEY ( CARRERA, CARNET ) ;

CREATE TABLE PENSUM
    (
     CURSO_CODIGOCURSO    NUMBER (5)  NOT NULL ,
     PLAN_PLAN            VARCHAR2 (20)  NOT NULL ,
     PLAN_CARRERA_CARRERA NUMBER (5)  NOT NULL ,
     OBLIGATORIEDAD       NUMBER (1)  NOT NULL ,
     NUMCREDITOS          NUMBER (5)  NOT NULL ,
     NOTAAPROBACION       NUMBER (5,2)  NOT NULL ,
     ZONAMINIMA           NUMBER (5,2)  NOT NULL ,
     CREDPRERREQUISITOS   NUMBER (5)  NOT NULL
    )
    LOGGING
;

ALTER TABLE PENSUM
    ADD CONSTRAINT CHK_CREDP
    CHECK (NUMCREDITOS > 0)
;


ALTER TABLE PENSUM
    ADD CONSTRAINT CHK_OBLIG
    CHECK (OBLIGATORIEDAD IN (0, 1))
;


ALTER TABLE PENSUM
    ADD CONSTRAINT PENSUM_CK_3
    CHECK (ADD CONSTRAINT CHK_NOTAAPROBACION_RANGO
    CHECK (NOTAAPROBACION >= 0 AND NOTAAPROBACION <= 100);
ADD CONSTRAINT CHK_ZONAMINIMA_RANGO
    CHECK (ZONAMINIMA >= 0 AND ZONAMINIMA <= 100);
ADD CONSTRAINT CHK_CREDPRERREQ_POSITIVO
    CHECK (CREDPRERREQUISITOS >= 0);
)
;
ALTER TABLE PENSUM
    ADD CONSTRAINT PENSUM_PK PRIMARY KEY ( CURSO_CODIGOCURSO, PLAN_PLAN, PLAN_CARRERA_CARRERA ) ;

CREATE TABLE PERIODO
    (
     PERIODO       NUMBER (5)  NOT NULL ,
     HORARIOINICIO VARCHAR2 (10)  NOT NULL ,
     HORARIOFINAL  VARCHAR2 (10)  NOT NULL
    )
    LOGGING
;

ALTER TABLE PERIODO
    ADD CONSTRAINT PERIODO_PK PRIMARY KEY ( PERIODO ) ;

CREATE TABLE PLAN
    (
     PLAN              VARCHAR2 (20)  NOT NULL ,
     CARRERA           NUMBER (5)  NOT NULL ,
     NOMBRE            VARCHAR2 (100)  NOT NULL ,
     ANIOINICIAL       NUMBER (4)  NOT NULL ,
     CICLOINICIAL      VARCHAR2 (10)  NOT NULL ,
     ANIOFINAL         NUMBER (4)  NOT NULL ,
     CICLOFINAL        VARCHAR2 (10)  NOT NULL ,
     NUMCREDITOSCIERRE NUMBER (5)  NOT NULL
    )
    LOGGING
;

ALTER TABLE PLAN
    ADD CONSTRAINT CHK_CREDCIERRE
    CHECK (NUMCREDITOSCIERRE > 0)
;


ALTER TABLE PLAN
    ADD CONSTRAINT PLAN_CK_2
    CHECK (ADD CONSTRAINT CHK_ANIOS_PLAN
    CHECK (ANIOINICIAL < ANIOFINAL OR
          (ANIOINICIAL = ANIOFINAL AND CICLOINICIAL != CICLOFINAL));)
;
ALTER TABLE PLAN
    ADD CONSTRAINT PLAN_PK PRIMARY KEY ( PLAN, CARRERA ) ;

CREATE TABLE PRERREQ
    (
     PENSUM_CARRERA     NUMBER (5)  NOT NULL ,
     PENSUM_PLAN        VARCHAR2 (20)  NOT NULL ,
     PENSUM_CURSO       NUMBER (5)  NOT NULL ,
     CURSO_PREREQUISITO NUMBER (5)  NOT NULL
    )
    LOGGING
;

ALTER TABLE PRERREQ
    ADD CONSTRAINT PRERREQ_PK PRIMARY KEY ( PENSUM_CARRERA, PENSUM_PLAN, PENSUM_CURSO, CURSO_PREREQUISITO ) ;

CREATE TABLE SALON
    (
     EDIFICIO  VARCHAR2 (10)  NOT NULL ,
     SALON     NUMBER (5)  NOT NULL ,
     CAPACIDAD NUMBER (4)  NOT NULL
    )
    LOGGING
;

ALTER TABLE SALON
    ADD CONSTRAINT CHK_CAPACIDAD
    CHECK (CAPACIDAD > 0)
;
ALTER TABLE SALON
    ADD CONSTRAINT SALON_PK PRIMARY KEY ( EDIFICIO, SALON ) ;

CREATE TABLE SECCION
    (
     SECCION                 VARCHAR2 (5)  NOT NULL ,
     ANIO                    NUMBER (4)  NOT NULL ,
     CICLO                   VARCHAR2 (10)  NOT NULL ,
     CURSO_CODIGOCURSO       NUMBER (5)  NOT NULL ,
     CATEDRATICO_CATEDRATICO NUMBER (5)  NOT NULL
    )
    LOGGING
;

ALTER TABLE SECCION
    ADD CONSTRAINT SECCION_PK PRIMARY KEY ( SECCION, ANIO, CICLO, CURSO_CODIGOCURSO ) ;

ALTER TABLE ASIGNACION
    ADD CONSTRAINT ASIGNACION_ESTUD_FK FOREIGN KEY
    (
     ESTUDIANTE_CARNET
    )
    REFERENCES ESTUDIANTE
    (
     CARNET
    )
    NOT DEFERRABLE
;

ALTER TABLE ASIGNACION
    ADD CONSTRAINT ASIGNACION_SECCION_FK FOREIGN KEY
    (
     SECCION_SECCION,
     SECCION_ANIO,
     SECCION_CICLO,
     SECCION_CODIGOCURSO
    )
    REFERENCES SECCION
    (
     SECCION,
     ANIO,
     CICLO,
     CURSO_CODIGOCURSO
    )
    NOT DEFERRABLE
;

ALTER TABLE HORARIO
    ADD CONSTRAINT HORARIO_DIA_FK FOREIGN KEY
    (
     DIA_DIA
    )
    REFERENCES DIA
    (
     DIA
    )
    NOT DEFERRABLE
;

ALTER TABLE HORARIO
    ADD CONSTRAINT HORARIO_PERIODO_FK FOREIGN KEY
    (
     PERIODO_PERIODO
    )
    REFERENCES PERIODO
    (
     PERIODO
    )
    NOT DEFERRABLE
;

ALTER TABLE HORARIO
    ADD CONSTRAINT HORARIO_SALON_FK FOREIGN KEY
    (
     SALON_EDIFICIO,
     SALON_SALON
    )
    REFERENCES SALON
    (
     EDIFICIO,
     SALON
    )
    NOT DEFERRABLE
;

ALTER TABLE HORARIO
    ADD CONSTRAINT HORARIO_SECCION_FK FOREIGN KEY
    (
     SECCION_SECCION,
     SECCION_ANIO,
     SECCION_CICLO,
     SECCION_CURSO_CODIGOCURSO
    )
    REFERENCES SECCION
    (
     SECCION,
     ANIO,
     CICLO,
     CURSO_CODIGOCURSO
    )
    NOT DEFERRABLE
;

ALTER TABLE INSCRIPCION
    ADD CONSTRAINT INSCRIPCION_CARRERA_FK FOREIGN KEY
    (
     CARRERA
    )
    REFERENCES CARRERA
    (
     CARRERA
    )
    NOT DEFERRABLE
;

ALTER TABLE INSCRIPCION
    ADD CONSTRAINT INSCRIPCION_ESTUD_FK FOREIGN KEY
    (
     CARNET
    )
    REFERENCES ESTUDIANTE
    (
     CARNET
    )
    NOT DEFERRABLE
;

ALTER TABLE PENSUM
    ADD CONSTRAINT PENSUM_CURSO_FK FOREIGN KEY
    (
     CURSO_CODIGOCURSO
    )
    REFERENCES CURSO
    (
     CODIGOCURSO
    )
    NOT DEFERRABLE
;

ALTER TABLE PENSUM
    ADD CONSTRAINT PENSUM_PLAN_FK FOREIGN KEY
    (
     PLAN_PLAN,
     PLAN_CARRERA_CARRERA
    )
    REFERENCES PLAN
    (
     PLAN,
     CARRERA
    )
    NOT DEFERRABLE
;

ALTER TABLE PLAN
    ADD CONSTRAINT PLAN_CARRERA_FK FOREIGN KEY
    (
     CARRERA
    )
    REFERENCES CARRERA
    (
     CARRERA
    )
    NOT DEFERRABLE
;

ALTER TABLE PRERREQ
    ADD CONSTRAINT PRERREQ_CURSO_FK FOREIGN KEY
    (
     CURSO_PREREQUISITO
    )
    REFERENCES CURSO
    (
     CODIGOCURSO
    )
    NOT DEFERRABLE
;

ALTER TABLE PRERREQ
    ADD CONSTRAINT PRERREQ_PENSUM_FK FOREIGN KEY
    (
     PENSUM_CURSO,
     PENSUM_PLAN,
     PENSUM_CARRERA
    )
    REFERENCES PENSUM
    (
     CURSO_CODIGOCURSO,
     PLAN_PLAN,
     PLAN_CARRERA_CARRERA
    )
    NOT DEFERRABLE
;

ALTER TABLE SECCION
    ADD CONSTRAINT SECCION_CATED_FK FOREIGN KEY
    (
     CATEDRATICO_CATEDRATICO
    )
    REFERENCES CATEDRATICO
    (
     CATEDRATICO
    )
    NOT DEFERRABLE
;

ALTER TABLE SECCION
    ADD CONSTRAINT SECCION_CURSO_FK FOREIGN KEY
    (
     CURSO_CODIGOCURSO
    )
    REFERENCES CURSO
    (
     CODIGOCURSO
    )
    NOT DEFERRABLE
;



-- Informe de Resumen de Oracle SQL Developer Data Modeler:
--
-- CREATE TABLE                            14
-- CREATE INDEX                             0
-- ALTER TABLE                             38
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0

--REGLA 1

CREATE OR REPLACE VIEW V_CURSOS_APROBADOS AS
SELECT 
    A.ESTUDIANTE_CARNET,
    A.SECCION_CODIGOCURSO AS CODIGOCURSO,
    I.CARRERA,
    P.PLAN_PLAN AS PLAN,
    A.ZONA,
    A.NOTA,
    P.NUMCREDITOS
FROM ASIGNACION A
JOIN INSCRIPCION I ON A.ESTUDIANTE_CARNET = I.CARNET
JOIN PENSUM P ON A.SECCION_CODIGOCURSO = P.CURSO_CODIGOCURSO 
             AND I.CARRERA = P.PLAN_CARRERA_CARRERA
WHERE A.ZONA >= P.ZONAMINIMA 
  AND A.NOTA >= P.NOTAAPROBACION
  -- Validar que todos los prerrequisitos estén aprobados
  AND NOT EXISTS (
      SELECT 1 FROM PRERREQ PR
      WHERE PR.PENSUM_CURSO    = P.CURSO_CODIGOCURSO
        AND PR.PENSUM_PLAN     = P.PLAN_PLAN
        AND PR.PENSUM_CARRERA  = P.PLAN_CARRERA_CARRERA
        AND NOT EXISTS (
            SELECT 1 FROM ASIGNACION A2
            JOIN PENSUM P2 
                ON A2.SECCION_CODIGOCURSO = P2.CURSO_CODIGOCURSO
                AND P2.PLAN_CARRERA_CARRERA = I.CARRERA
            WHERE A2.ESTUDIANTE_CARNET = A.ESTUDIANTE_CARNET
              AND A2.SECCION_CODIGOCURSO = PR.CURSO_PREREQUISITO
              AND A2.NOTA >= P2.NOTAAPROBACION
              AND A2.ZONA >= P2.ZONAMINIMA
        )
  )
  -- Validar créditos prerrequisito acumulados
  AND (
      SELECT NVL(SUM(P3.NUMCREDITOS), 0)
      FROM ASIGNACION A3
      JOIN PENSUM P3 
          ON A3.SECCION_CODIGOCURSO = P3.CURSO_CODIGOCURSO
          AND P3.PLAN_CARRERA_CARRERA = I.CARRERA
      WHERE A3.ESTUDIANTE_CARNET = A.ESTUDIANTE_CARNET
        AND A3.NOTA >= P3.NOTAAPROBACION
        AND A3.ZONA >= P3.ZONAMINIMA
  ) >= P.CREDPRERREQUISITOS;

  --REGLA 2

  CREATE OR REPLACE VIEW V_PROMEDIO_ESTUDIANTE AS
SELECT 
    ESTUDIANTE_CARNET,
    CARRERA,
    PLAN,
    ROUND(AVG(NOTA), 2) AS PROMEDIO_GENERAL
FROM V_CURSOS_APROBADOS
GROUP BY 
    ESTUDIANTE_CARNET, 
    CARRERA, 
    PLAN;

    --REGLA 3

CREATE OR REPLACE VIEW V_ESTUDIANTES_CIERRE AS
WITH CreditosEstudiante AS (
    SELECT 
        ESTUDIANTE_CARNET,
        CARRERA,
        PLAN,
        SUM(NUMCREDITOS) AS CREDITOS_ACUMULADOS
    FROM V_CURSOS_APROBADOS
    GROUP BY ESTUDIANTE_CARNET, CARRERA, PLAN
),
CursosObligatoriosFaltantes AS (
    SELECT 
        I.CARNET,
        P_PLAN.CARRERA,   -- <-- agregar CARRERA aquí
        P_PLAN.PLAN,
        COUNT(P_OBLIG.CURSO_CODIGOCURSO) AS FALTANTES
    FROM INSCRIPCION I
    JOIN PLAN P_PLAN ON I.CARRERA = P_PLAN.CARRERA
    JOIN PENSUM P_OBLIG 
        ON P_PLAN.PLAN    = P_OBLIG.PLAN_PLAN 
        AND P_PLAN.CARRERA = P_OBLIG.PLAN_CARRERA_CARRERA
    WHERE P_OBLIG.OBLIGATORIEDAD = 1
      AND P_OBLIG.CURSO_CODIGOCURSO NOT IN (
          SELECT CODIGOCURSO 
          FROM V_CURSOS_APROBADOS CA 
          WHERE CA.ESTUDIANTE_CARNET = I.CARNET 
            AND CA.CARRERA = I.CARRERA
      )
    GROUP BY I.CARNET, P_PLAN.CARRERA, P_PLAN.PLAN
)
SELECT 
    C.ESTUDIANTE_CARNET AS CARNET,
    C.CARRERA,
    C.PLAN,
    C.CREDITOS_ACUMULADOS,
    PL.NUMCREDITOSCIERRE
FROM CreditosEstudiante C
JOIN PLAN PL ON C.PLAN = PL.PLAN AND C.CARRERA = PL.CARRERA
LEFT JOIN CursosObligatoriosFaltantes COF 
    ON C.ESTUDIANTE_CARNET = COF.CARNET 
    AND C.CARRERA = COF.CARRERA   -- <-- join por carrera también
    AND C.PLAN = COF.PLAN
WHERE C.CREDITOS_ACUMULADOS >= PL.NUMCREDITOSCIERRE
  AND NVL(COF.FALTANTES, 0) = 0
  AND EXTRACT(YEAR FROM SYSDATE) <= PL.ANIOFINAL; -- vigencia del plan

-- REGLA 4

  CREATE OR REPLACE VIEW V_MEJOR_ESTUDIANTE AS
WITH EstudiantesConReprobados AS (
    -- Identificamos a los que han perdido al menos un curso
    SELECT DISTINCT A.ESTUDIANTE_CARNET
    FROM ASIGNACION A
    JOIN INSCRIPCION I ON A.ESTUDIANTE_CARNET = I.CARNET
    JOIN PENSUM P ON A.SECCION_CODIGOCURSO = P.CURSO_CODIGOCURSO 
                 AND I.CARRERA = P.PLAN_CARRERA_CARRERA
    WHERE A.NOTA IS NOT NULL 
      AND (A.ZONA < P.ZONAMINIMA OR A.NOTA < P.NOTAAPROBACION)
)
SELECT 
    PE.ESTUDIANTE_CARNET,
    E.NOMBRE,
    PE.CARRERA,
    PE.PROMEDIO_GENERAL
FROM V_PROMEDIO_ESTUDIANTE PE
JOIN ESTUDIANTE E ON PE.ESTUDIANTE_CARNET = E.CARNET
WHERE PE.ESTUDIANTE_CARNET NOT IN (SELECT ESTUDIANTE_CARNET FROM EstudiantesConReprobados)
ORDER BY PE.PROMEDIO_GENERAL DESC
FETCH FIRST 1 ROWS ONLY;